env:
  browser: true
  commonjs: true
  es6: true
  node: true
extends: 'eslint:recommended'
rules:
  indent:
    - error
    - tab
    - SwitchCase: 1
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - always
  no-trailing-spaces: "error"
  no-console: 0
parserOptions:
  sourceType: "module"
